#ifndef CONF_FILE_CONSTANTS_H
#define CONF_FILE_CONSTANTS_H


#ifndef FSQLF_CONFFILE_NAME
#define FSQLF_CONFFILE_NAME "formatting.conf"
#endif

#ifndef FSQLF_CONFFILE_LINELENGTH
#define FSQLF_CONFFILE_LINELENGTH (100)
#endif


#endif
